/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddFilmForm.java
 *
 * Created on Apr 4, 2013, 10:38:02 PM
 */
package com.unit7.videocollection.forms;

import com.unit7.videocollection.entities.Director;
import com.unit7.videocollection.entities.Film;
import com.unit7.videocollection.entities.Genre;
import com.unit7.videocollection.entities.Studio;
import com.unit7.videocollection.forms.processors.FormProcessor;
import com.unit7.videocollection.utils.HibernateUtil;
import com.unit7.videocollection.utils.impl.FilmFieldGetterImpl;
import com.unit7.videocollection.utils.impl.FilmFieldSetterImpl;
import javax.swing.SwingUtilities;

/**
 *
 * @author unit7
 */
public class FilmListForm extends javax.swing.JFrame {

    /** Creates new form AddFilmForm */
    public FilmListForm() {
        initComponents();
        filmTable1.refresh();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VideoCollectionPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("VideoCollectionPU").createEntityManager();
        filmQuery = java.beans.Beans.isDesignTime() ? null : VideoCollectionPUEntityManager.createQuery("SELECT f FROM Film f");
        filmList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : filmQuery.getResultList();
        filmQuery1 = java.beans.Beans.isDesignTime() ? null : VideoCollectionPUEntityManager.createQuery("SELECT f FROM Film f");
        filmList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : filmQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filmTable1 = new com.unit7.videocollection.utils.components.FilmTable();
        addFilm = new javax.swing.JButton();
        refreshTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        filmTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        filmTable1.setName("filmTable1"); // NOI18N
        jScrollPane1.setViewportView(filmTable1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.unit7.videocollection.VideoCollectionApp.class).getContext().getResourceMap(FilmListForm.class);
        addFilm.setText(resourceMap.getString("addFilm.text")); // NOI18N
        addFilm.setName("addFilm"); // NOI18N
        addFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilmActionPerformed(evt);
            }
        });

        refreshTable.setText(resourceMap.getString("refreshTable.text")); // NOI18N
        refreshTable.setName("refreshTable"); // NOI18N
        refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTable)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFilm)
                    .addComponent(refreshTable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void addFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilmActionPerformed
    SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                final FilmAddForm form = new FilmAddForm();
                form.setVisible(true);
                
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        Object[] info = FormProcessor.getInfo(form);
                        form.dispose();
                        
                        Film film = new Film();

                        film.setTitle((String) info[0]);
                        film.setDescription((String) info[4]);
                        film.setGenre((Genre) info[1]);
                        film.setDirector((Director) info[2]);
                        film.setStudio((Studio) info[3]);

                        HibernateUtil.insertEntity(film, new FilmFieldSetterImpl(), new FilmFieldGetterImpl());
                    }
                }).start();
            }
        });
}//GEN-LAST:event_addFilmActionPerformed

private void refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTableActionPerformed
    filmTable1.refresh();
}//GEN-LAST:event_refreshTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FilmListForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager VideoCollectionPUEntityManager;
    private javax.swing.JButton addFilm;
    private java.util.List<com.unit7.videocollection.entities.Film> filmList;
    private java.util.List<com.unit7.videocollection.entities.Film> filmList1;
    private javax.persistence.Query filmQuery;
    private javax.persistence.Query filmQuery1;
    private com.unit7.videocollection.utils.components.FilmTable filmTable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTable;
    // End of variables declaration//GEN-END:variables
}
